type = "publication"
title = "Publications"
description = "Authors are generally listed alphabetically, as customary in cryptography. For papers with non-alphabetical author order, * denotes first or co-first authorship."
source = "publications.bib"
