type = "publication"
title = "Publications"
description = "Publications below are listed in alphabetical order (either among all authors or among student authors), unless marked with *, which denotes the main contributor.\nPapers without a URL are currently in preparation for ePrint and will be available soon."
source = "publications.bib"
